version: '3.9'

services:
  app:
    depends_on:
      - postgres
    image: app-hls
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    networks:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
  postgres:
    image: postgres:15-alpine
    build: ./database
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db
volumes:
  app:
  pgdata:
networks:
  db:
    driver: bridge
